"""Removed Letter Grade

Revision ID: a743ccce47c9
Revises: 98b948da22bd
Create Date: 2025-07-15 20:08:17.523015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a743ccce47c9'
down_revision: Union[str, None] = '98b948da22bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assignment_grades', 'letter_grade')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignment_grades', sa.Column('letter_grade', sa.VARCHAR(), nullable=False))
    # ### end Alembic commands ###
